# Generated by Django 3.2.11 on 2022-01-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='categoty',
            new_name='category',
        ),
    ]
