# Generated by Django 3.2.11 on 2022-01-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_module', '0002_auto_20220114_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='name',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
